title = "New Directions Publishers"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "thenewdynamic-hugo-core-theme"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 500 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
#disableKinds = ["page","section", "taxonomy", "taxonomyTerm"]
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = ""
  description_long = "New Directions was founded in 1936, when James Laughlin (1914–1997), then a twenty-two-year-old Harvard sophomore, issued the first of the New Directions anthologies. “I asked Ezra Pound for ‘career advice,’” Laughlin recalled. “He had been seeing my poems for months and had ruled them hopeless. He urged me to finish Harvard and then do ‘something’ useful.”"
  facebook = "https://www.facebook.com/ndbooks"
  twitter = "https://twitter.com/NewDirections"
  instagram = ""
  youtube = ""
  amp = false
  body_classes = "sans-serif bg-near-white"
  #headerClasses = "bg-purple mid-gray"
